version: "3"
services:
  app:
    build: ./app
    depends_on:
      - xpublish
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
  xpublish:
    build: ./xpublish
    expose:
      - 9000
